version: '3.8'
services:
  db:
    image: mysql:latest
    container_name: mysqlDatabase
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=Admin@123
      # - MYSQL_DATABASE=mysql-docker
    volumes:
      - /C/working/docker/mysql/:/var/lib/mysql