version: "3.7"
services:
  pgsql:
    container_name: pgsql
    image: 'bitnami/postgresql:latest'
    environment:
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_PASSWORD=postgres
      - POSTGRESQL_DATABASE=postgres
    # volumes:
      #- "./init_db.sql:/docker-entrypoint-initdb.d"
    ports:
      - "5432:5432"
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: nobody@rogers.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
